name: Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - staging
          - prod

jobs:
  mage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true

      - name: Run app locally
        run: mage runLocal
